language: node_js

branches.only:
  - master

cache:
  npm: true
  directories:
    - node_modules

node_js: '13'

before_deploy:
  - cd "dist/lib"

jobs:
  include:
    - stage: prepare
      name: "Install dependencies"
      script: npm install
    - stage: build
      name: build
      script: npm run build:lib
    - stage: deploy
      name: "Run deployment"
      deploy:
        provider: npm
        email: marajulind@outlook.com
        skip_cleanup: true
        api_key: $API_TOKEN
        on: deploy-npm-release

stages:
  - prepare
  - build
  - deploy
